services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/zaq1@WSX
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    container_name: recommender-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTH_USERNAME=neo4j
      - SPRING_NEO4J_AUTH_PASSWORD=zaq1@WSX
      - JWT_SECRET=my-super-secret-key-which-is-long-enough-123456
    depends_on:
      - neo4j
    restart: unless-stopped

  frontend:
    build:
      context: ./gui
      dockerfile: ../docker/gui/Dockerfile
    container_name: recommender-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped