spring:
  application:
    name: recommender
  data:
    neo4j:
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: "zaq1@WSX"

jwt:
  secret: "my-super-secret-key-which-is-long-enough-123456"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method