spring:
  application:
    name: recommender

  data:
    neo4j:
      database: neo4j

  neo4j:
    uri: ${SPRING_NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${SPRING_NEO4J_AUTH_USERNAME:neo4j}
      password: ${SPRING_NEO4J_AUTH_PASSWORD:zaq1@WSX}

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-which-is-long-enough-123456}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
